name: craft
recipe: lamp
config:
  webroot: web
  php: '8.1'
  composer_version: 2
  database: mariadb:10.5
services:
  database:
    type: mariadb:10.5
    portforward: 3311
    creds:
      user: craft
      password: craft
      database: craft
